version: 2
jobs:
  run_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: install dependencies.
          command: |
            sudo pip install poetry
            poetry install --dev
      - run:
          name: running tests
          command: |
            poetry run pytest -vv
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_test
