version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.9

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            poetry install -v

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Run Pytest,
          command: |
            poetry run pytest -vv --cov=airflow_k8s_operator tests/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
